# Generated by Django 6.1.1 on 2026-09-13 22:40

import pools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(default=pools.models.generate_short_code, editable=False, max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=56)),
                ('title', models.CharField(max_length=140)),
                ('goal_amount', models.CharField(blank=True, max_length=32, null=True)),
                ('creator', models.CharField(max_length=56)),
                ('donation_count', models.PositiveIntegerField(default=0)),
                ('total_donated_by_asset', models.JSONField(blank=True, default=dict)),
                ('donations_synced_cursor', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
