# Generated by Django 6.1.1 on 2026-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_pool_vault_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
