# Generated by Django 6.1.1 on 2026-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_account', models.CharField(max_length=56, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('creator', models.CharField(max_length=56)),
                ('signers', models.JSONField()),
                ('med_threshold', models.PositiveSmallIntegerField()),
                ('high_threshold', models.PositiveSmallIntegerField()),
                ('withdrawal_limit', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
