# Generated by Django 6.1.1 on 2026-09-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPoolDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositor', models.CharField(max_length=56)),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='family_pools.familypool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
