# Generated by Django 6.1.1 on 2026-09-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_pools', '0002_familypooldeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='familypool',
            name='blend_principal',
            field=models.CharField(blank=True, default='0', max_length=32),
        ),
    ]
