# Generated by Django 6.1.1 on 2026-09-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=56)),
                ('receiver', models.CharField(max_length=56)),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='payments_pa_sender_88ee78_idx'), models.Index(fields=['receiver'], name='payments_pa_receive_a6a28a_idx')],
            },
        ),
    ]
