# Generated by Django 6.1.1 on 2026-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, max_length=56)),
                ('receiver', models.CharField(max_length=56)),
                ('amount', models.CharField(max_length=32)),
                ('asset_code', models.CharField(default='XLM', max_length=8)),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=16)),
                ('next_run_at', models.DateTimeField()),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=140)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['sender', 'active'], name='payments_re_sender_97eb34_idx')],
            },
        ),
    ]
